version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simplechat-test"
s3_bucket = "aws-sam-cli-managed-testchat-samclisourcebucket"
s3_prefix = "testchat"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_test\""