/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:25d759f7-8ab5-4edb-991a-c0367736d452",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_umizVK1md",
    "aws_user_pools_web_client_id": "4uajsjbto95uqvvvnq9r2lsvut",
    "oauth": {}
};


export default awsmobile;
