/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a9395a50-e5a8-4c1f-a3e6-90920949180b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DP1sgZ1FC",
    "aws_user_pools_client_id": "2h9vuffn6urim68lujmtsqfv1f",
    "aws_s3_bucket": "seminar-profile-photos",
    "aws_s3_bucket_region": "us-east-1"
};


export default config;
