/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1"

    "aws_cognito_identity_pool_id": "us-east-1:48c506cc-ecbc-40af-826d-aea48fbf7a5b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9NBO8j4CN",
    "aws_user_pools_client_id": "7hvjh3o427hj2ei4gc6aaf6r5b",
    "aws_user_pools_web_client_id": "6cosnrr4cf2ku2gta3b28bkjc",
};


export default awsmobile;
