/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_poll_id": "us-east-1:741520ef-3bc3-4907-af04-ffdedec2028d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7DzzGN91J",
    "aws_user_pools_client_id": "27galunsed5ne6m240i5h82km3",
    "aws_appsync_graphqlEndpoint": "https://qssh4niq5bgujocnsbpv2zg7am.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    /* "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS", */
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_s3_bucket": "seminar-profile-photos",
    "aws_s3_bucket_region": "us-east-1"
    /* "aws_appsync_apiKey": "da2-iqwe4wuf7jhezprwwtrc7b4zua" */
};


export default awsmobile;
